spring:
  config:
    import: optional:file:env.properties

  application:
    name: tripchat

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

  session:
    store-type: ${SESSION_STORE}
    redis:
      namespace: ${SESSION_NAME}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  address: 0.0.0.0