spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

  session:
    store-type: ${SESSION_STORE}
    redis:
      namespace: ${SESSION_NAME}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
